# Generated by Django 3.1.3 on 2020-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=500)),
                ('categories', models.CharField(choices=[('FA', 'Fashion'), ('HG', 'Home & Garden'), ('EL', 'Electronics'), ('HE', 'Home Entertainment'), ('TO', 'Toys'), ('CO', 'Collectables')], max_length=2)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
