# Generated by Django 3.1.3 on 2020-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201127_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
