# Generated by Django 3.1.3 on 2020-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionauthor',
            field=models.CharField(default='ojs', max_length=64),
            preserve_default=False,
        ),
    ]
