# Generated by Django 3.1.3 on 2020-11-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_minimumbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionclosed',
            field=models.BooleanField(default=False),
        ),
    ]
