# Generated by Django 3.1.3 on 2020-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_auctionclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionwinner',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
